name: myknott
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bubble: ^1.2.1
  carousel_slider: ^4.1.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.5
  date_format: ^2.0.6
  dio: ^4.0.6
  file_picker: ^3.0.4
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_facebook_auth: ^4.3.4+2
  flutter_linkify: ^5.0.2
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  google_maps_flutter: ^2.1.8
  google_sign_in: ^5.3.3
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lazy_load_scrollview: ^1.3.0
  permission_handler: ^10.0.0
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  table_calendar: ^3.0.6
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/userr.png
    - assets/user.png
    - assets/chat.png
    - assets/caller.png
    - assets/location.png
    - assets/logo.png
    - assets/appointment.png
    - assets/appointment1.png
    - assets/brown.jpg
    - assets/Error.png
    - assets/404.svg
    - assets/noUserFound.png

  fonts:
    - family: Whitney
      fonts:
        - asset: fonts/Whitney-Book.otf
