name: myknott
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^3.0.1
  future_button: ^0.1.2
  connectivity: ^3.0.3
  font_awesome_flutter:
  dio: ^4.0.0-prev2
  firebase_auth: ^1.0.1
  salomon_bottom_bar: ^3.0.0
  firebase_storage: ^10.0.5
  firebase_core: ^1.0.1
  timelines:
  timeline_tile:
  flutter_secure_storage:
  intl:
  sliding_up_panel: ^1.0.2
  google_maps_flutter:
  shared_preferences:
  table_calendar:
  cached_network_image:
  cupertino_icons: ^1.0.2
  firebase_messaging: ^10.0.8
  url_launcher: ^6.0.2
  image_picker: ^0.7.4
  fluttertoast: ^8.0.4
  lazy_load_scrollview: ^1.3.0
  bubble: ^1.2.1
  emoji_picker_flutter: any
  permission_handler: ^7.0.0
  google_sign_in: ^5.0.1
  flutter_easyloading: ^3.0.0
  flutter_facebook_auth: ^3.2.0
  flutter_svg: ^0.21.0-nullsafety.0
  date_format: ^2.0.4
  carousel_slider: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Whitney
      fonts:
        - asset: fonts/Whitney-Book.otf
